'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SkinName() As String
            Get
                Return CType(Me("SkinName"),String)
            End Get
            Set
                Me("SkinName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Palette() As String
            Get
                Return CType(Me("Palette"),String)
            End Get
            Set
                Me("Palette") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CompactMode() As Boolean
            Get
                Return CType(Me("CompactMode"),Boolean)
            End Get
            Set
                Me("CompactMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LavenderBlush")>  _
        Public Property C1() As Global.System.Drawing.Color
            Get
                Return CType(Me("C1"),Global.System.Drawing.Color)
            End Get
            Set
                Me("C1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property C2() As Global.System.Drawing.Color
            Get
                Return CType(Me("C2"),Global.System.Drawing.Color)
            End Get
            Set
                Me("C2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property A() As Integer
            Get
                Return CType(Me("A"),Integer)
            End Get
            Set
                Me("A") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property G() As Integer
            Get
                Return CType(Me("G"),Integer)
            End Get
            Set
                Me("G") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ResetClrs() As Integer
            Get
                Return CType(Me("ResetClrs"),Integer)
            End Get
            Set
                Me("ResetClrs") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DBase\Dentist"& _ 
            "X.mdf;Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property DentistXConnectionString1() As String
            Get
                Return CType(Me("DentistXConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=DentistX;Trusted_Connection=SSPI;Encrypt=false;Trus"& _ 
            "tServerCertificate=true")>  _
        Public ReadOnly Property DentistXConnectionString() As String
            Get
                Return CType(Me("DentistXConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RememberMe() As Boolean
            Get
                Return CType(Me("RememberMe"),Boolean)
            End Get
            Set
                Me("RememberMe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Scan() As String
            Get
                Return CType(Me("Scan"),String)
            End Get
            Set
                Me("Scan") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DBase\Dentist"& _ 
            "X.mdf;Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property DentistXConnectionString2() As String
            Get
                Return CType(Me("DentistXConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UseHdrTestModHeader() As Boolean
            Get
                Return CType(Me("UseHdrTestModHeader"),Boolean)
            End Get
            Set
                Me("UseHdrTestModHeader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastWeeklyBackupDate() As String
            Get
                Return CType(Me("LastWeeklyBackupDate"),String)
            End Get
            Set
                Me("LastWeeklyBackupDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BackupOnExit() As Boolean
            Get
                Return CType(Me("BackupOnExit"),Boolean)
            End Get
            Set
                Me("BackupOnExit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Naming() As Boolean
            Get
                Return CType(Me("Naming"),Boolean)
            End Get
            Set
                Me("Naming") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ShortReminder() As Short
            Get
                Return CType(Me("ShortReminder"),Short)
            End Get
            Set
                Me("ShortReminder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FinanceDashboardPasswordSalt() As String
            Get
                Return CType(Me("FinanceDashboardPasswordSalt"),String)
            End Get
            Set
                Me("FinanceDashboardPasswordSalt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property FinanceDashboardPasswordHash() As String
            Get
                Return CType(Me("FinanceDashboardPasswordHash"),String)
            End Get
            Set
                Me("FinanceDashboardPasswordHash") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("07:00:00")>  _
        Public Property SchedulerWorkingDayStart() As Global.System.TimeSpan
            Get
                Return CType(Me("SchedulerWorkingDayStart"),Global.System.TimeSpan)
            End Get
            Set
                Me("SchedulerWorkingDayStart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20:00:00")>  _
        Public Property SchedulerWorkingDayEnd() As Global.System.TimeSpan
            Get
                Return CType(Me("SchedulerWorkingDayEnd"),Global.System.TimeSpan)
            End Get
            Set
                Me("SchedulerWorkingDayEnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UiLanguage() As String
            Get
                Return CType(Me("UiLanguage"),String)
            End Get
            Set
                Me("UiLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastCrashWhatsReportSignature() As String
            Get
                Return CType(Me("LastCrashWhatsReportSignature"),String)
            End Get
            Set
                Me("LastCrashWhatsReportSignature") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property ApptModuleCardStartTimeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ApptModuleCardStartTimeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ApptModuleCardStartTimeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SteelBlue")>  _
        Public Property ApptModuleCardEndTimeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ApptModuleCardEndTimeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ApptModuleCardEndTimeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33, 37, 41")>  _
        Public Property ApptModuleCardPatientNameColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ApptModuleCardPatientNameColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ApptModuleCardPatientNameColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 118, 128")>  _
        Public Property ApptModuleCardReasonColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ApptModuleCardReasonColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ApptModuleCardReasonColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("93, 64, 140")>  _
        Public Property ApptModuleCardNotesColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ApptModuleCardNotesColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ApptModuleCardNotesColor") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DentistX.My.MySettings
            Get
                Return Global.DentistX.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
