USE [DentistX]
GO

/****** Object:  Table [dbo].[AppSetngs]    Script Date: 30/03/2026 1:30:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AppSetngs](
	[SettingKey] [nvarchar](100) NOT NULL,
	[SettingValue] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_AppSetngs] PRIMARY KEY CLUSTERED 
(
	[SettingKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Forms](
	[FormID] [int] IDENTITY(1,1) NOT NULL,
	[FormName] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](255) NULL,
 CONSTRAINT [PK_Forms] PRIMARY KEY CLUSTERED 
(
	[FormID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[FormName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Groups](
	[GroupID] [int] IDENTITY(1,1) NOT NULL,
	[GroupName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Groups] PRIMARY KEY CLUSTERED 
(
	[GroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Groups_GroupName] UNIQUE NONCLUSTERED 
(
	[GroupName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[GroupPermissions](
	[GroupID] [int] NOT NULL,
	[PermID] [int] NOT NULL,
	[IsAllowed] [bit] NOT NULL,
 CONSTRAINT [PK_GroupPermissions] PRIMARY KEY CLUSTERED 
(
	[GroupID] ASC,
	[PermID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GroupPermissions] ADD  DEFAULT ((1)) FOR [IsAllowed]
GO

ALTER TABLE [dbo].[GroupPermissions]  WITH CHECK ADD  CONSTRAINT [FK_GP_Groups] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Groups] ([GroupID])
GO

ALTER TABLE [dbo].[GroupPermissions] CHECK CONSTRAINT [FK_GP_Groups]
GO

ALTER TABLE [dbo].[GroupPermissions]  WITH CHECK ADD  CONSTRAINT [FK_GP_Permissions] FOREIGN KEY([PermID])
REFERENCES [dbo].[Permissions] ([PermID])
GO

ALTER TABLE [dbo].[GroupPermissions] CHECK CONSTRAINT [FK_GP_Permissions]
GO

CREATE TABLE [dbo].[Permissions](
	[PermID] [int] IDENTITY(1,1) NOT NULL,
	[PermKey] [nvarchar](100) NULL,
	[PermName] [nvarchar](100) NOT NULL,
	[PermDescription] [nvarchar](255) NULL,
	[Category] [nvarchar](100) NULL,
	[IsActive] [bit] NULL,
	[CreatedAt] [datetime2](7) NULL,
 CONSTRAINT [PK__Permissi__29C30A7C1B665BB4] PRIMARY KEY CLUSTERED 
(
	[PermID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Permissions] ADD  CONSTRAINT [DF_Permissions_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Permissions] ADD  CONSTRAINT [DF_Permissions_CreatedAt]  DEFAULT (sysdatetime()) FOR [CreatedAt]
GO

CREATE TABLE [dbo].[USERS](
	[UsID] [int] IDENTITY(1,1) NOT NULL,
	[UsName] [nvarchar](50) NOT NULL,
	[UsPassHash] [varbinary](50) NOT NULL,
	[UsSalt] [varbinary](50) NOT NULL,
	[GroupID] [int] NOT NULL,
	[UsLvl] [int] NOT NULL,
	[UsGrp] [nvarchar](50) NOT NULL,
	[DrID] [int] NULL,
	[SecID] [int] NULL,
	[EmpID] [int] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_Users_Doctors] FOREIGN KEY([DrID])
REFERENCES [dbo].[Doctors] ([DrID])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_Users_Doctors]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_Emp] FOREIGN KEY([EmpID])
REFERENCES [dbo].[Emp] ([EmpID])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_Emp]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_Users_Groups] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Groups] ([GroupID])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_Users_Groups]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_Users_Secretaries] FOREIGN KEY([SecID])
REFERENCES [dbo].[Secretaries] ([SecID])
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_Users_Secretaries]
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [CK_USERS_cid] CHECK  (([GroupID]=(1) AND ([DrID] IS NULL OR [DrID] IS NOT NULL) OR ([SecID] IS NULL OR [SecID] IS NOT NULL) OR ([EmpID] IS NULL OR [EmpID] IS NOT NULL) OR [GroupID]=(2) AND [DrID] IS NOT NULL AND [SecID] IS NULL AND [EmpID] IS NULL OR [GroupID]=(3) AND [SecID] IS NOT NULL AND [DrID] IS NULL AND [EmpID] IS NULL OR [GroupID]=(4) AND [EmpID] IS NOT NULL AND [DrID] IS NULL AND [SecID] IS NULL))
GO

ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [CK_USERS_cid]
GO


CREATE TABLE [dbo].[UserPermissions](
	[UsID] [int] NOT NULL,
	[PermID] [int] NOT NULL,
	[IsAllowed] [bit] NOT NULL,
 CONSTRAINT [PK_UserPermissions] PRIMARY KEY CLUSTERED 
(
	[UsID] ASC,
	[PermID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UserPermissions]  WITH CHECK ADD  CONSTRAINT [FK_UP_Permissions] FOREIGN KEY([PermID])
REFERENCES [dbo].[Permissions] ([PermID])
GO

ALTER TABLE [dbo].[UserPermissions] CHECK CONSTRAINT [FK_UP_Permissions]
GO

ALTER TABLE [dbo].[UserPermissions]  WITH CHECK ADD  CONSTRAINT [FK_UP_Users] FOREIGN KEY([UsID])
REFERENCES [dbo].[USERS] ([UsID])
GO

ALTER TABLE [dbo].[UserPermissions] CHECK CONSTRAINT [FK_UP_Users]
GO



