
/****** Object:  Table [dbo].[Bracets]    Script Date: 08/05/2026 6:05:33 PM ******/

CREATE TABLE [dbo].[Bracets](
	[BracetID] [int] IDENTITY(1,1) NOT NULL,
	[BracetName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Bracets] PRIMARY KEY CLUSTERED 
(
	[BracetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[BracetName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Fixers]    Script Date: 08/05/2026 6:05:54 PM ******/

CREATE TABLE [dbo].[Fixers](
	[FixerID] [int] IDENTITY(1,1) NOT NULL,
	[FixerName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Fixers] PRIMARY KEY CLUSTERED 
(
	[FixerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[FixerName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[OrthoTypes]    Script Date: 08/05/2026 6:06:10 PM ******/

CREATE TABLE [dbo].[OrthoTypes](
	[OrthoTypeID] [int] IDENTITY(1,1) NOT NULL,
	[OrthoTypeName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_OrthoTypes] PRIMARY KEY CLUSTERED 
(
	[OrthoTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[OrthoTypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TblMeasure]    Script Date: 08/05/2026 6:06:24 PM ******/

CREATE TABLE [dbo].[TblMeasure](
	[MeasureID] [int] IDENTITY(1,1) NOT NULL,
	[Measure] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TblMeasure] PRIMARY KEY CLUSTERED 
(
	[MeasureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[TblWireType]    Script Date: 08/05/2026 6:06:37 PM ******/

CREATE TABLE [dbo].[TblWireType](
	[TypeID] [int] IDENTITY(1,1) NOT NULL,
	[WireType] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TblWireType] PRIMARY KEY CLUSTERED 
(
	[TypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


