Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports DevExpress.DataAccess
Imports DevExpress.DashboardCommon

Namespace Win_Dashboards
    Partial Public Class Dashboard1
        Inherits DevExpress.DashboardCommon.Dashboard
        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            PatientTableAdapter1.Fill(MainDS1.Patient)
        End Sub
    End Class
End Namespace